
-- EJERCICIO 1
SELECT COUNT(*) AS "Total Registros"
    FROM INSCRITOS;


-- EJERCICIO 2
SELECT SUM(CANTIDAD) AS "Cantidad de Inscritos"
    FROM INSCRITOS;

-- EJERCICIO 3
SELECT * 
    FROM iNSCRITOS
    WHERE FECHA = (
        SELECT MIN(FECHA) 
            FROM INSCRITOS
        );



-- EJERCICIO 4
SELECT  SUM(CANTIDAD) AS "Cantidad de Inscritos",
        FECHA
    FROM INSCRITOS
    GROUP BY 
        FECHA;


-- EJERCICIO 5
SELECT  SUM(CANTIDAD) AS "Cantidad de Inscritos",
        FUENTE
    FROM INSCRITOS
    GROUP BY 
        FUENTE;


-- EJERCICIO 6

SELECT SUM(CANTIDAD) AS CANT_INSCRITOS,
        FECHA
    FROM INSCRITOS
    GROUP BY 
    FECHA
    ORDER BY CANT_INSCRITOS DESC
    lIMIT 1;



-- EJERCICIO 7
SELECT SUM(CANTIDAD) AS CANT_INSCRITOS,
        FUENTE
    FROM INSCRITOS
    WHERE FUENTE = 'Blog'
    GROUP BY FUENTE
    ORDER BY CANT_INSCRITOS DESC
    lIMIT 1;


-- EJERCICIO 8
SELECT  AVG(CANTIDAD) AS "Promedio de Inscritos",
        FECHA
    FROM INSCRITOS
    GROUP BY 
        FECHA;


-- EJERCICIO 9
SELECT CANTIDAD, 
       FECHA 
    FROM INSCRITOS 
    WHERE CANTIDAD > 50;


-- EJERCICIO 10
SELECT  AVG(CANTIDAD) AS "Promedio de Inscritos",
        FECHA
    FROM INSCRITOS
    WHERE FECHA > '2021/03/01'
    GROUP BY 
        FECHA;